# Generated by Django 5.0.2 on 2024-09-11 19:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('instagram', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('twitter', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('youtube', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
