# Generated by Django 5.0.2 on 2024-09-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_tournamentenrollment_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentenrollment',
            name='placement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
