# Generated by Django 5.0.2 on 2024-09-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_whyjoinus'),
    ]

    operations = [
        migrations.CreateModel(
            name='how_it_works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_1', models.CharField(max_length=100)),
                ('step_1_description', models.CharField(max_length=100)),
                ('step_1_image', models.ImageField(upload_to='how_it_works/')),
                ('step_2', models.CharField(max_length=100)),
                ('step_2_description', models.CharField(max_length=100)),
                ('step_2_image', models.ImageField(upload_to='how_it_works/')),
                ('step_3', models.CharField(max_length=100)),
                ('step_3_description', models.CharField(max_length=100)),
                ('step_3_image', models.ImageField(upload_to='how_it_works/')),
            ],
        ),
    ]
